# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: pretty-format-json
        exclude: 'package-lock.json'
        args: ["--no-sort-keys", "--no-ensure-ascii"]
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.4
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
